### POST signup
POST https://{{host}}:{{port}}/auth/register
Content-Type: application/json

{
  "username":"Allen Hardy",
  "email":{{email2}},
  "password":{{password2}},
  "confirmPassword":{{password2}}
}

### POST Login
POST https://{{host}}:{{port}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
### GET request to ExileModels Server root - this is a list of application routes
GET https://{{host}}:{{port}}
Authorization: Bearer {{token}}

### GET request to list serial ports
GET https://{{host}}:{{port}}/serial
Authorization: Bearer {{token}}
